version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: abuubaida
      POSTGRES_PASSWORD: abuubaida
      POSTGRES_DB: abuubaida
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
volumes:
  pgdata:
